name = "sk8-scoop"
main = "worker.js"
compatibility_date = "2026-07-24"
keep_vars = true

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = [ "/api/*" ]
html_handling = "auto-trailing-slash"

# Cloudflare will provision and bind a D1 database for this Worker.
[[d1_databases]]
binding = "DB"
